### ISSUE TITLE
Hello! May I ask a question about the "mpirun"?

### ISSUE THREAD

**Issue by 92cser** [phicau/OLAFOAM#2]
Hi, phicau:

I am a student from China, and I also a user of IHFoam, as well as olaFoam. After study your code, I have developed my own BC and it works well with interDyMFoam. Lately, I have compiled a new solver, but there is one problem: 

The solver works well with single core but it cannot run parallel. 

Accurately, it can run parallel without error on the terminal, but the result is wrong obviously. And when using paraView to see the decomposePar result, it says:

"Found duplicated entries with keyword value ".

And I found the mesh does not update in the pimple loop : 

// This is the code in solver:
 if (pimple.firstIter() || moveMeshOuterCorrectors)
            {
                scalar timeBeforeMeshUpdate = runTime.elapsedCpuTime();

                mesh.update();

                if (mesh.changing())                      **//Here comes the problem!**
                {
                    Info<< "Execution time for mesh.update() = "
                        << runTime.elapsedCpuTime() - timeBeforeMeshUpdate
                        << " s" << endl;

                    gh = (g & mesh.C()) - ghRef;
                    ghf = (g & mesh.Cf()) - ghRef;
                }

                if (mesh.changing() && correctPhi)
                {
                    // Calculate absolute flux from the mapped surface velocity
                    phi = mesh.Sf() & Uf;

                    #include "correctPhi.H"

                    // Make the flux relative to the mesh motion
                    fvc::makeRelative(phi, U);

                    mixture.correct();
                }

                if (mesh.changing() && checkMeshCourantNo)
                {
                    #include "meshCourantNo.H"
                }
The program does not goes into the first "if(mesh.changing())". I believe that there must be a problem of the patch named "processor" after decomposePar. But I did not change anything in solver, which means the code  is same with interDyMFoam.C and olaFoam.C. And my BC could run parallel well with interDyMFoam.

I cannot solve this problem. So I will be very grateful if you could give me some advice.

Best regards,

Dongxu Wang 
Email : wdx_cfd@163.com/21140216@qq.com

**Comment by phicau** [comment]
This place is for reporting bugs in the olaFoam project, not a support forum
